--------------------------------------------------------
--  File created - Wednesday-October-16-2024
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DOC_CATEGORY
--------------------------------------------------------

CREATE TABLE LICENSE_CATEGORY(
    "CATE_ID" NUMBER,
	"CATE_NAME" VARCHAR2(100 BYTE)
);
Insert into LICENSE_CATEGORY (CATE_ID,CATE_NAME) values (1,'License');
Insert into LICENSE_CATEGORY (CATE_ID,CATE_NAME) values (2,'Certificate');
Insert into LICENSE_CATEGORY (CATE_ID,CATE_NAME) values (3,'Contract');
Insert into LICENSE_CATEGORY (CATE_ID,CATE_NAME) values (4,'Agreement');
Insert into LICENSE_CATEGORY (CATE_ID,CATE_NAME) values (5,'Compliance');

--------------------------------------------------------
--  DDL for Table LICENSE_TEMPLATE
--------------------------------------------------------
CREATE TABLE LICENSE_TEMPLATE(
    "DOCID" NUMBER,
	"DOCNO" NVARCHAR2(10),
	"DOCNAME" NVARCHAR2(100),
	"DOCCATEGORY" NUMBER,
	"DOCTERM" NUMBER,
	"DOCTERMUNIT" NVARCHAR2(5),
	"DOCALERT" NUMBER,
    "DOCPIC" NVARCHAR2(5),
    "DOCDIV" NVARCHAR2(6),
    "DOCDEPT" NVARCHAR2(6),
    "DOCSEC" NVARCHAR2(6),
    "DOCLEVEL" NVARCHAR2(6),
	"EXTENDED" NVARCHAR2(1),
    "CREATEDATE" TIMESTAMP (6) DEFAULT sysdate,
    "CREATEBY" NVARCHAR2(5),
    "UPDATEDATE" TIMESTAMP (6),
    "UPDATEBY" NVARCHAR2(5)
);

CREATE SEQUENCE SEQ_LICENSE_MSTCOLUMN MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE OR REPLACE TRIGGER LICENSE_TEMPLATE_DOCID
BEFORE INSERT ON LICENSE_TEMPLATE
FOR EACH ROW
BEGIN
    IF :NEW.DOCID IS NULL THEN
        SELECT SEQ_LICENSE_MSTCOLUMN.NEXTVAL INTO :NEW.DOCID FROM dual;
    END IF;
END;
--------------------------------------------------------
--  DDL for Table LICENSE_MSTALERT
--------------------------------------------------------
CREATE TABLE LICENSE_MSTALERT (
    "ALTDOC" NUMBER,
	"ALTEMP" NVARCHAR2(5)
);

--------------------------------------------------------
--  DDL for Table LICENSE_MSTCOLUMN
--------------------------------------------------------
CREATE TABLE LICENSE_MSTCOLUMN(
    "COLID" NUMBER,
	"COLDOC" NUMBER,
	"COLNAME" NVARCHAR2(100),
	"COLTYPE" NVARCHAR2(20)
);

CREATE SEQUENCE SEQ_LICENSE_MSTCOLUMN MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE OR REPLACE TRIGGER LICENSE_MSTCOLUMN_COLID
BEFORE INSERT ON LICENSE_MSTCOLUMN
FOR EACH ROW
BEGIN
    IF :NEW.COLID IS NULL THEN
        SELECT SEQ_LICENSE_MSTCOLUMN.NEXTVAL INTO :NEW.COLID FROM dual;
    END IF;
END;
--------------------------------------------------------
--  DDL for Table LICENSE_MSTOPTION
--------------------------------------------------------
CREATE TABLE LICENSE_MSTOPTION(
    "OPTID" NUMBER,
	"OPTCOLUMN" NUMBER,
	"OPTVALUE" NVARCHAR2(100)
);

CREATE SEQUENCE SEQ_LICENSE_MSTOPTION MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE OR REPLACE TRIGGER LICENSE_MSTOPTION_OPTID
BEFORE INSERT ON LICENSE_MSTOPTION
FOR EACH ROW
BEGIN
    IF :NEW.OPTID IS NULL THEN
        SELECT SEQ_LICENSE_MSTOPTION.NEXTVAL INTO :NEW.OPTID FROM dual;
    END IF;
END;

--------------------------------------------------------
--  DDL for Table LICENSE
--------------------------------------------------------
CREATE TABLE LICENSE(
    LSID NUMBER,
    LSNO NVARCHAR2(10),
    LSCODE NVARCHAR2(10),
    LSTITLE NVARCHAR2(100),
    LSCATEGORY NUMBER,
    LSPROVIDERCODE NVARCHAR2(5),
    LSPROVIDERNAME NVARCHAR2(5),
    LSPIC NVARCHAR2(5),
    LSSTART DATE,
    LSEXPIRE DATE,
    LSTERM NUMBER,
    LSTERMUNIT NVARCHAR2(5),
    LSALERT NUMBER,
    LSALERTDATE DATE,
    LSSTATUS    NVARCHAR2(1),
    LSCREATEDATE TIMESTAMP (6) DEFAULT sysdate,
    LSCREATEBY NVARCHAR2(5),
    LSUPDATEDATE TIMESTAMP (6),
    LSUPDATEBY NVARCHAR2(5),
    LSLATEST char(1)
);

CREATE SEQUENCE SEQ_LICENSE MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE OR REPLACE TRIGGER LICENSE_LSID
BEFORE INSERT ON LICENSE
FOR EACH ROW
BEGIN
    IF :NEW.LSID IS NULL THEN
        SELECT SEQ_LICENSE.NEXTVAL INTO :NEW.LSID FROM dual;
    END IF;
END;

--------------------------------------------------------
--  DDL for Table LICENSE_ADDITIONAL
--------------------------------------------------------
CREATE TABLE LICENSE_ADDITIONAL(
    "LSADID" NUMBER,
    "LICENSE" NUMBER,
    "LSADCOL" NVARCHAR2(100),
    "LSADVALUE" NVARCHAR2(100)
);

CREATE SEQUENCE SEQ_LICENSE_ADDITIONAL MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE OR REPLACE TRIGGER LICENSE_ADDITIONAL_LSADID
BEFORE INSERT ON LICENSE_ADDITIONAL
FOR EACH ROW
BEGIN
    IF :NEW.LSADID IS NULL THEN
        SELECT SEQ_LICENSE_ADDITIONAL.NEXTVAL INTO :NEW.LSADID FROM dual;
    END IF;
END;